# Generated by Django 5.2.10 on 2026-01-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="giftcard",
            new_name="promotions__code_bcdb8e_idx",
            old_name="promotio_gi_code_j1k2l3_idx",
        ),
        migrations.RenameIndex(
            model_name="giftcard",
            new_name="promotions__status_74b229_idx",
            old_name="promotio_gi_status_m4n5o6_idx",
        ),
        migrations.RenameIndex(
            model_name="giftcard",
            new_name="promotions__owner_i_dc3cc6_idx",
            old_name="promotio_gi_owner_p7q8r9_idx",
        ),
        migrations.RenameIndex(
            model_name="giftcard",
            new_name="promotions__valid_u_24fbf6_idx",
            old_name="promotio_gi_valid_u_s1t2u3_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="promotions__code_88fd84_idx",
            old_name="promotio_vo_code_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="promotions__status_3aca02_idx",
            old_name="promotio_vo_status_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="voucher",
            new_name="promotions__valid_f_38cc0d_idx",
            old_name="promotio_vo_valid_f_g7h8i9_idx",
        ),
    ]
