# Generated by Django 5.2.11 on 2026-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_remove_productorder_vouchers_and_more"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voucherusage",
            name="voucher",
        ),
        migrations.RemoveField(
            model_name="voucherusage",
            name="user",
        ),
        migrations.DeleteModel(
            name="Voucher",
        ),
        migrations.DeleteModel(
            name="VoucherUsage",
        ),
    ]
