# Generated by Django 5.2.10 on 2026-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "promotions",
            "0002_rename_promotio_gi_code_j1k2l3_idx_promotions__code_bcdb8e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="recipient_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number of recipient",
                max_length=20,
                verbose_name="recipient phone",
            ),
        ),
    ]
