# Generated by Django 5.2.11 on 2026-02-24 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_remove_productorder_vouchers_and_more"),
        (
            "promotions",
            "0002_remove_voucherusage_voucher_remove_voucherusage_user_and_more",
        ),
        ("spacenter", "0004_service_is_eligible_for_loyalty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="redeemed at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for no expiry",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "earned_from_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earned_loyalty_rewards",
                        to="bookings.booking",
                        verbose_name="earned from booking",
                    ),
                ),
                (
                    "redeemed_in_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_loyalty_rewards",
                        to="bookings.booking",
                        verbose_name="redeemed in booking",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_rewards",
                        to="spacenter.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "loyalty reward",
                "verbose_name_plural": "loyalty rewards",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="promotions__custome_df527e_idx",
                    ),
                    models.Index(
                        fields=["service", "status"],
                        name="promotions__service_63a599_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of paid bookings since last reward or start",
                        verbose_name="booking count",
                    ),
                ),
                (
                    "bookings_required",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Number of paid bookings needed to earn a free booking",
                        verbose_name="bookings required",
                    ),
                ),
                (
                    "total_bookings",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lifetime count of qualifying paid bookings",
                        verbose_name="total bookings",
                    ),
                ),
                (
                    "total_rewards_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lifetime count of loyalty rewards earned",
                        verbose_name="total rewards earned",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_trackers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_trackers",
                        to="spacenter.service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "loyalty tracker",
                "verbose_name_plural": "loyalty trackers",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "service"],
                        name="promotions__custome_abbcdc_idx",
                    )
                ],
                "unique_together": {("customer", "service")},
            },
        ),
    ]
