# Generated by Django 5.2.11 on 2026-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_remove_productorder_gift_cards"),
        ("promotions", "0003_loyaltyreward_loyaltytracker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="gift_card",
        ),
        migrations.RemoveField(
            model_name="giftcardtemplate",
            name="country",
        ),
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="GiftCard",
        ),
        migrations.DeleteModel(
            name="GiftCardTemplate",
        ),
        migrations.DeleteModel(
            name="GiftCardTransaction",
        ),
    ]
