# Generated by Django 5.2.11 on 2026-02-26 10:13

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import promotions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_productorder_gift_cards'),
        ('promotions', '0004_remove_giftcardtransaction_gift_card_and_more'),
        ('spacenter', '0004_service_is_eligible_for_loyalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the gift recipient (E.164 format)', max_length=128, region=None, verbose_name='recipient phone number')),
                ('recipient_name', models.CharField(blank=True, help_text='Optional display name for the recipient', max_length=150, verbose_name='recipient name')),
                ('gift_message', models.TextField(blank=True, help_text='Optional personal message from the sender', verbose_name='gift message')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price paid for the gifted service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', models.CharField(default='QAR', max_length=3, verbose_name='currency')),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for this gift card purchase', max_length=255, verbose_name='Stripe Payment Intent')),
                ('secret_code', models.CharField(default=promotions.models.generate_secret_code, help_text='6-digit secret code sent to recipient via SMS', max_length=6, verbose_name='secret code')),
                ('public_token', models.CharField(db_index=True, default=promotions.models.generate_public_token, help_text='Token used in the public gift card page URL', max_length=32, unique=True, verbose_name='public token')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20, verbose_name='status')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True, verbose_name='expires at')),
                ('sms_sent', models.BooleanField(default=False, help_text='Whether the SMS with secret code has been sent', verbose_name='SMS sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='SMS sent at')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='failed redemption attempts')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='max redemption attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('redeemed_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_redemptions', to='bookings.booking', verbose_name='redeemed in booking')),
                ('redeemed_by', models.ForeignKey(blank=True, help_text='System user who redeemed the gift card (if they exist)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='redeemed by')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='spacenter.service', verbose_name='gifted service')),
                ('spa_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='spacenter.spacenter', verbose_name='spa center')),
            ],
            options={
                'verbose_name': 'gift card',
                'verbose_name_plural': 'gift cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='promotions__sender__cf441f_idx'), models.Index(fields=['recipient_phone', 'status'], name='promotions__recipie_a214d0_idx'), models.Index(fields=['public_token'], name='promotions__public__f5f81d_idx'), models.Index(fields=['status', 'created_at'], name='promotions__status_c7098f_idx')],
            },
        ),
    ]
