# Generated by Django 5.2.11 on 2026-02-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_add_gift_card_model'),
        ('spacenter', '0004_service_is_eligible_for_loyalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='extra_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Extra minutes added to the service duration', verbose_name='extra minutes'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='service_arrangement',
            field=models.ForeignKey(blank=True, help_text='Room/setup configuration for the gifted service', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_cards', to='spacenter.servicearrangement', verbose_name='service arrangement'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='total_duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration in minutes (service duration + extra minutes)', verbose_name='total duration (minutes)'),
        ),
    ]
