# Generated by Django 5.2.11 on 2026-03-02 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0006_replace_stripe_with_arrangement_duration"),
        ("spacenter", "0004_service_is_eligible_for_loyalty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="loyaltytracker",
            name="promotions__custome_abbcdc_idx",
        ),
        migrations.AlterUniqueTogether(
            name="loyaltytracker",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="loyaltyreward",
            name="service_arrangement",
            field=models.ForeignKey(
                blank=True,
                help_text="Room/setup configuration for this loyalty reward",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_rewards",
                to="spacenter.servicearrangement",
                verbose_name="service arrangement",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytracker",
            name="service_arrangement",
            field=models.ForeignKey(
                blank=True,
                help_text="Room/setup configuration for this loyalty tracker",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_trackers",
                to="spacenter.servicearrangement",
                verbose_name="service arrangement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loyaltytracker",
            unique_together={("customer", "service", "service_arrangement")},
        ),
        migrations.AddIndex(
            model_name="loyaltytracker",
            index=models.Index(
                fields=["customer", "service", "service_arrangement"],
                name="promotions__custome_3668e9_idx",
            ),
        ),
    ]
