# Generated by Django 5.2.11 on 2026-03-02 07:18

import promotions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "promotions",
            "0007_remove_loyaltytracker_promotions__custome_abbcdc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltyreward",
            name="expires_at",
            field=models.DateTimeField(
                default=promotions.models.default_reward_expiry,
                help_text="Reward expires after this date and cannot be redeemed. Defaults to 10 days after creation. Admin can adjust.",
                verbose_name="expires at",
            ),
        ),
    ]
