# Generated by Django 5.2.11 on 2026-03-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0008_alter_loyaltyreward_expires_at"),
        ("spacenter", "0004_service_is_eligible_for_loyalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="service_arrangement",
            field=models.ForeignKey(
                help_text="Room/setup configuration for the gifted service",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_cards",
                to="spacenter.servicearrangement",
                verbose_name="service arrangement",
            ),
        ),
    ]
