# Generated by Django 5.2.11 on 2026-04-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0010_add_giftcard_fulfilled_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("active", "Active"),
                    ("redeemed", "Redeemed"),
                    ("fulfilled", "Service Fulfilled"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
