# Generated by Django 5.2.11 on 2026-04-23 08:28

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import promotions.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_historicalbooking'),
        ('promotions', '0011_alter_giftcard_status'),
        ('spacenter', '0010_historicalservice_historicalservicearrangement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGiftCard',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the gift recipient (E.164 format)', max_length=128, region=None, verbose_name='recipient phone number')),
                ('recipient_name', models.CharField(blank=True, help_text='Optional display name for the recipient', max_length=150, verbose_name='recipient name')),
                ('gift_message', models.TextField(blank=True, help_text='Optional personal message from the sender', verbose_name='gift message')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price paid for the gifted service', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', models.CharField(default='QAR', max_length=3, verbose_name='currency')),
                ('extra_minutes', models.PositiveIntegerField(default=0, help_text='Extra minutes added to the service duration', verbose_name='extra minutes')),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total duration in minutes (service duration + extra minutes)', verbose_name='total duration (minutes)')),
                ('secret_code', models.CharField(default=promotions.models.generate_secret_code, help_text='6-digit secret code sent to recipient via SMS', max_length=6, verbose_name='secret code')),
                ('public_token', models.CharField(db_index=True, default=promotions.models.generate_public_token, help_text='Token used in the public gift card page URL', max_length=32, verbose_name='public token')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('redeemed', 'Redeemed'), ('fulfilled', 'Service Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20, verbose_name='status')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='Timestamp when the recipient visited the spa and enjoyed the service', null=True, verbose_name='fulfilled at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True, verbose_name='expires at')),
                ('sms_sent', models.BooleanField(default=False, help_text='Whether the SMS with secret code has been sent', verbose_name='SMS sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='SMS sent at')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='failed redemption attempts')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='max redemption attempts')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fulfilled_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Staff member who marked the service as fulfilled', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='fulfilled by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('redeemed_booking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.booking', verbose_name='redeemed in booking')),
                ('redeemed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='System user who redeemed the gift card (if they exist)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='redeemed by')),
                ('sender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.service', verbose_name='gifted service')),
                ('service_arrangement', models.ForeignKey(blank=True, db_constraint=False, help_text='Room/setup configuration for the gifted service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.servicearrangement', verbose_name='service arrangement')),
                ('spa_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.spacenter', verbose_name='spa center')),
            ],
            options={
                'verbose_name': 'historical gift card',
                'verbose_name_plural': 'historical gift cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLoyaltyReward',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20, verbose_name='status')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('expires_at', models.DateTimeField(default=promotions.models.default_reward_expiry, help_text='Reward expires after this date and cannot be redeemed. Defaults to 10 days after creation. Admin can adjust.', verbose_name='expires at')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('earned_from_booking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.booking', verbose_name='earned from booking')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('redeemed_in_booking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.booking', verbose_name='redeemed in booking')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.service', verbose_name='service')),
                ('service_arrangement', models.ForeignKey(blank=True, db_constraint=False, help_text='Room/setup configuration for this loyalty reward', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.servicearrangement', verbose_name='service arrangement')),
            ],
            options={
                'verbose_name': 'historical loyalty reward',
                'verbose_name_plural': 'historical loyalty rewards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLoyaltyTracker',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('booking_count', models.PositiveIntegerField(default=0, help_text='Number of paid bookings since last reward or start', verbose_name='booking count')),
                ('bookings_required', models.PositiveIntegerField(default=5, help_text='Number of paid bookings needed to earn a free booking', verbose_name='bookings required')),
                ('total_bookings', models.PositiveIntegerField(default=0, help_text='Lifetime count of qualifying paid bookings', verbose_name='total bookings')),
                ('total_rewards_earned', models.PositiveIntegerField(default=0, help_text='Lifetime count of loyalty rewards earned', verbose_name='total rewards earned')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.service', verbose_name='service')),
                ('service_arrangement', models.ForeignKey(blank=True, db_constraint=False, help_text='Room/setup configuration for this loyalty tracker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.servicearrangement', verbose_name='service arrangement')),
            ],
            options={
                'verbose_name': 'historical loyalty tracker',
                'verbose_name_plural': 'historical loyalty trackers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
