# Generated by Django 5.2.11 on 2026-05-04 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0012_historicalgiftcard_historicalloyaltyreward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='System user who is the intended recipient of this gift card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='historicalgiftcard',
            name='recipient',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='System user who is the intended recipient of this gift card', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
    ]
