# Generated by Django 5.2.11 on 2026-05-04 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_historicalbooking'),
        ('promotions', '0013_add_recipient_to_giftcard'),
        ('spacenter', '0011_historicalservice_description_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['recipient', 'status'], name='promotions__recipie_e6f2b1_idx'),
        ),
    ]
