# Generated by Django 5.2.11 on 2026-06-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0014_add_recipient_index_to_giftcard'),
        ('spacenter', '0016_service_session_benefits_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='add_on_service',
            field=models.ForeignKey(blank=True, help_text='Optional add-on service gifted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='spacenter.addonservice', verbose_name='add-on service'),
        ),
        migrations.AddField(
            model_name='historicalgiftcard',
            name='add_on_service',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional add-on service gifted', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.addonservice', verbose_name='add-on service'),
        ),
    ]
