# Generated by Django 5.2.11 on 2026-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0015_giftcard_add_on_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('active', 'Active'), ('redeemed', 'Redeemed'), ('fulfilled', 'Service Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalgiftcard',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_failed', 'Payment Failed'), ('active', 'Active'), ('redeemed', 'Redeemed'), ('fulfilled', 'Service Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20, verbose_name='status'),
        ),
    ]
