# Generated by Django 5.2.10 on 2026-01-22 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='URL to the slide image', max_length=500, verbose_name='image URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('link', models.URLField(blank=True, help_text='URL to navigate to when slide is clicked', max_length=500, verbose_name='link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Only active slides are displayed', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
