# Generated by Django 5.2.11 on 2026-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("branch_manager", "Branch Manager"),
                    ("country_manager", "Country Manager"),
                ],
                db_index=True,
                default="branch_manager",
                max_length=30,
                verbose_name="role",
            ),
        ),
    ]
