# Generated by Django 5.2.10 on 2026-01-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_slide_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slide',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, help_text='Slide image', null=True, upload_to='slides/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
