# Generated by Django 5.2.11 on 2026-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_employeeprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=10,
                verbose_name="gender",
            ),
        ),
    ]
