# Generated by Django 5.2.11 on 2026-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_customerprofile_dob_customerprofile_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeschedule',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
