# Generated by Django 5.2.11 on 2026-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20, verbose_name='user type'),
        ),
    ]
