# Generated by Django 5.2.11 on 2026-04-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
        ('spacenter', '0009_remove_homeservice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spa_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='spacenter.spacenter', verbose_name='assigned spa center'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('customer', 'Customer')], db_index=True, default='customer', max_length=20, verbose_name='user type'),
        ),
    ]
