# Generated by Django 5.2.11 on 2026-05-04 11:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicaluser'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spacenter', '0011_historicalservice_description_ar_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='email_or_phone_required',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='+0000000000', max_length=128, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='+0000000000', max_length=128, region=None, unique=True, verbose_name='phone number'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('phone_number__isnull', False)), name='phone_required'),
        ),
    ]
