# Generated by Django 5.2.11 on 2026-05-04 11:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_make_phone_mandatory_step1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='phone number'),
        ),
    ]
