# Generated by Django 5.2.11 on 2026-05-05 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_temporary_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='reason for deletion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='admin notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data deletion request',
                'verbose_name_plural': 'data deletion requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
