# Generated by Django 5.2.10 on 2026-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_for_female',
            field=models.BooleanField(default=True, verbose_name='for female'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_for_male',
            field=models.BooleanField(default=False, verbose_name='for male'),
        ),
    ]
