# Generated by Django 5.2.10 on 2026-01-12 09:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="category name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="category name",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="category name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={
                ("country", "name"),
                ("country", "name_ar"),
                ("country", "name_en"),
            },
        ),
        migrations.CreateModel(
            name="BaseProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product name")),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="product name"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=255, null=True, verbose_name="product name"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="short description"
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_ar",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Product"),
                            ("service_addon", "Service Add-on"),
                            ("consumable", "Consumable"),
                        ],
                        default="retail",
                        max_length=20,
                        verbose_name="product type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. Oils, Skincare, Aromatherapy",
                        max_length=100,
                        verbose_name="category",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="brand"),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit",
                        max_length=100,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="spa_products/",
                        verbose_name="image",
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(default=False, verbose_name="organic"),
                ),
                (
                    "is_aromatherapy",
                    models.BooleanField(default=False, verbose_name="aromatherapy"),
                ),
                (
                    "suitable_for_sensitive_skin",
                    models.BooleanField(
                        default=False, verbose_name="suitable for sensitive skin"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="visible"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "base product",
                "verbose_name_plural": "base products",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="spacenter_b_name_5d239d_idx"),
                    models.Index(
                        fields=["category"], name="spacenter_b_categor_e3ffd9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="spacenter_b_status_2e580b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SpaProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "price_en",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "price_ar",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="discounted price",
                    ),
                ),
                (
                    "discounted_price_en",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="discounted price",
                    ),
                ),
                (
                    "discounted_price_ar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="discounted price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="QAR", max_length=10, verbose_name="currency"
                    ),
                ),
                (
                    "currency_en",
                    models.CharField(
                        default="QAR", max_length=10, null=True, verbose_name="currency"
                    ),
                ),
                (
                    "currency_ar",
                    models.CharField(
                        default="QAR", max_length=10, null=True, verbose_name="currency"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="quantity"),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For carts/orders not yet finalized",
                        verbose_name="reserved quantity",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5, verbose_name="low stock threshold"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spa_products",
                        to="spacenter.city",
                        verbose_name="city",
                    ),
                ),
                (
                    "city_ar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spa_products",
                        to="spacenter.city",
                        verbose_name="city",
                    ),
                ),
                (
                    "city_en",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spa_products",
                        to="spacenter.city",
                        verbose_name="city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spa_products",
                        to="spacenter.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "country_ar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spa_products",
                        to="spacenter.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "country_en",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spa_products",
                        to="spacenter.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="spacenter.baseproduct",
                        verbose_name="product",
                    ),
                ),
                (
                    "product_ar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="spacenter.baseproduct",
                        verbose_name="product",
                    ),
                ),
                (
                    "product_en",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="spacenter.baseproduct",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "spa product",
                "verbose_name_plural": "spa products",
                "ordering": ["-updated_at"],
                "unique_together": {
                    ("product", "country", "city"),
                    ("product", "country", "city_ar"),
                    ("product", "country", "city_en"),
                    ("product", "country_ar", "city"),
                    ("product", "country_en", "city"),
                    ("product_ar", "country", "city"),
                    ("product_en", "country", "city"),
                },
            },
        ),
    ]
