# Generated by Django 5.2.10 on 2026-01-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={
                ("country", "name"),
                ("country", "name_ar"),
                ("country", "name_en"),
            },
        ),
    ]
