# Generated by Django 5.2.11 on 2026-02-24 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0002_delete_therapistprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="extra_minutes",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_for_extra_minutes",
        ),
        migrations.AddField(
            model_name="servicearrangement",
            name="extra_minutes",
            field=models.CharField(
                choices=[
                    ("15", "15 minutes"),
                    ("30", "30 minutes"),
                    ("45", "45 minutes"),
                    ("60", "60 minutes"),
                ],
                default="0",
                max_length=10,
                verbose_name="extra minutes",
            ),
        ),
        migrations.AddField(
            model_name="servicearrangement",
            name="price_for_extra_minutes",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank to use base price for extra minutes",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="price for extra minutes",
            ),
        ),
    ]
