# Generated by Django 5.2.10 on 2026-01-14 09:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0002_productcategory_alter_city_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOnService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="add-on name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Additional time for this add-on",
                        verbose_name="duration (minutes)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="QAR", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/addons/",
                        verbose_name="image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "add-on service",
                "verbose_name_plural": "add-on services",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="spaproduct",
            unique_together={("product", "country", "city")},
        ),
        migrations.AddField(
            model_name="service",
            name="add_on_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional services that can be added to this service",
                related_name="services",
                to="spacenter.addonservice",
                verbose_name="add-on services",
            ),
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="city_ar",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="city_en",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="country_ar",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="country_en",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="currency_ar",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="currency_en",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="discounted_price_ar",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="discounted_price_en",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="price_ar",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="price_en",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="product_ar",
        ),
        migrations.RemoveField(
            model_name="spaproduct",
            name="product_en",
        ),
    ]
