# Generated by Django 5.2.11 on 2026-02-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0003_remove_service_extra_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_eligible_for_loyalty",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, successful bookings for this service count towards the loyalty program. After every 5 paid bookings, the customer earns one free booking of this service.",
                verbose_name="eligible for loyalty program",
            ),
        ),
    ]
