# Generated by Django 5.2.10 on 2026-01-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0003_addonservice_alter_spaproduct_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonservice",
            name="description_ar",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="addonservice",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="addonservice",
            name="name_ar",
            field=models.CharField(
                max_length=150, null=True, verbose_name="add-on name"
            ),
        ),
        migrations.AddField(
            model_name="addonservice",
            name="name_en",
            field=models.CharField(
                max_length=150, null=True, verbose_name="add-on name"
            ),
        ),
    ]
