# Generated by Django 5.2.10 on 2026-02-07 09:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0004_addonservice_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArrangement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_no', models.CharField(help_text='Room label for this arrangement', max_length=100, verbose_name='room number')),
                ('arrangement_type', models.CharField(choices=[('single_room', 'Single Room'), ('couple_room', 'Couple Room'), ('group_room', 'Group Room'), ('open_area', 'Open Area'), ('vip_suite', 'VIP Suite'), ('outdoor_arrangement', 'Outdoor Arrangement')], default='single_room', max_length=25, verbose_name='arrangement type')),
                ('arrangement_label', models.CharField(help_text='Display label for this arrangement', max_length=100, verbose_name='arrangement label')),
                ('cleanup_duration', models.PositiveIntegerField(default=15, help_text='Time needed to clean/prepare room after service', verbose_name='cleanup duration (minutes)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this arrangement type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price if applicable', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='spacenter.service', verbose_name='service')),
                ('spa_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_arrangements', to='spacenter.spacenter', verbose_name='spa center')),
            ],
            options={
                'verbose_name': 'service arrangement',
                'verbose_name_plural': 'service arrangements',
                'ordering': ['spa_center', 'service', 'room_no'],
                'indexes': [models.Index(fields=['spa_center', 'service', 'is_active'], name='spacenter_s_spa_cen_107ab1_idx'), models.Index(fields=['service', 'is_active'], name='spacenter_s_service_fbbfb4_idx')],
                'unique_together': {('spa_center', 'service', 'room_no')},
            },
        ),
    ]
