# Generated by Django 5.2.11 on 2026-03-31 06:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0004_service_is_eligible_for_loyalty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="service name")),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="service name"
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=200, null=True, verbose_name="service name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="duration (minutes)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if no discount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="discount price",
                    ),
                ),
                (
                    "is_for_male",
                    models.BooleanField(default=False, verbose_name="for male"),
                ),
                (
                    "is_for_female",
                    models.BooleanField(default=True, verbose_name="for female"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home_services/",
                        verbose_name="image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_services",
                        to="spacenter.city",
                        verbose_name="city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_services",
                        to="spacenter.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_home_services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_services",
                        to="spacenter.specialty",
                        verbose_name="specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "home service",
                "verbose_name_plural": "home services",
                "ordering": ["-created_at"],
            },
        ),
    ]
