# Generated by Django 5.2.11 on 2026-04-07 07:02

from django.db import migrations, models


def migrate_room_no_to_count(apps, schema_editor):
    ServiceArrangement = apps.get_model('spacenter', 'ServiceArrangement')
    for arr in ServiceArrangement.objects.all():
        try:
            # Extract numbers if present, otherwise default to 1
            import re
            room_no = getattr(arr, 'room_no', '1')
            match = re.search(r'\d+', room_no)
            if match:
                arr.room_count = int(match.group())
            else:
                arr.room_count = 1
        except Exception:
            arr.room_count = 1
        arr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0005_homeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearrangement',
            name='room_count',
            field=models.PositiveIntegerField(default=1, help_text='How many rooms/spaces are available for this arrangement', verbose_name='room count'),
        ),
        migrations.RunPython(migrate_room_no_to_count, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='servicearrangement',
            options={'ordering': ['spa_center', 'service', 'room_count'], 'verbose_name': 'service arrangement', 'verbose_name_plural': 'service arrangements'},
        ),
        migrations.AlterUniqueTogether(
            name='servicearrangement',
            unique_together={('spa_center', 'service', 'arrangement_type', 'arrangement_label')},
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='room_no',
        ),
    ]
