# Generated by Django 5.2.11 on 2026-04-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spacenter", "0006_alter_servicearrangement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_home_service",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price_for_home_service",
        ),
    ]
