# Generated by Django 5.2.11 on 2026-04-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0007_remove_service_is_home_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacenter',
            name='branch_manager',
        ),
    ]
