# Generated by Django 5.2.11 on 2026-04-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0008_remove_spacenter_branch_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeservice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
    ]
