# Generated by Django 5.2.11 on 2026-04-23 08:28

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0009_remove_homeservice_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalService',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='service name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duration (minutes)')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('QAR', 'Qatari Riyal'), ('KWD', 'Kuwaiti Dinar'), ('BHD', 'Bahraini Dinar'), ('OMR', 'Omani Rial'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='AED', max_length=3, verbose_name='currency')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if no discount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount price')),
                ('is_for_male', models.BooleanField(default=False, verbose_name='for male')),
                ('is_for_female', models.BooleanField(default=True, verbose_name='for female')),
                ('ideal_for', models.CharField(blank=True, help_text="e.g., 'Relaxation', 'Pain Relief', 'Couples'", max_length=255, verbose_name='ideal for')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefits as key-value pairs', verbose_name='benefits')),
                ('is_eligible_for_loyalty', models.BooleanField(default=False, help_text='If enabled, successful bookings for this service count towards the loyalty program. After every 5 paid bookings, the customer earns one free booking of this service.', verbose_name='eligible for loyalty program')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.city', verbose_name='city')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.country', verbose_name='country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('spa_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.spacenter', verbose_name='spa center')),
                ('specialty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.specialty', verbose_name='specialty')),
            ],
            options={
                'verbose_name': 'historical service',
                'verbose_name_plural': 'historical services',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServiceArrangement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('room_count', models.PositiveIntegerField(default=1, help_text='How many rooms/spaces are available for this arrangement', verbose_name='room count')),
                ('arrangement_type', models.CharField(choices=[('single_room', 'Single Room'), ('couple_room', 'Couple Room'), ('group_room', 'Group Room'), ('open_area', 'Open Area'), ('vip_suite', 'VIP Suite'), ('outdoor_arrangement', 'Outdoor Arrangement')], default='single_room', max_length=25, verbose_name='arrangement type')),
                ('arrangement_label', models.CharField(help_text='Display label for this arrangement', max_length=100, verbose_name='arrangement label')),
                ('cleanup_duration', models.PositiveIntegerField(default=15, help_text='Time needed to clean/prepare room after service', verbose_name='cleanup duration (minutes)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this arrangement type', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price if applicable', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount price')),
                ('extra_minutes', models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='0', max_length=10, verbose_name='extra minutes')),
                ('price_for_extra_minutes', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use base price for extra minutes', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price for extra minutes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.service', verbose_name='service')),
                ('spa_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.spacenter', verbose_name='spa center')),
            ],
            options={
                'verbose_name': 'historical service arrangement',
                'verbose_name_plural': 'historical service arrangements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSpaCenter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='branch name')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='image')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('default_opening_time', models.TimeField(default='09:00', verbose_name='default opening time')),
                ('default_closing_time', models.TimeField(default='21:00', verbose_name='default closing time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('on_service', models.BooleanField(default=True, help_text='Is currently operational', verbose_name='on service')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.city', verbose_name='city')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.country', verbose_name='country')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical spa center',
                'verbose_name_plural': 'historical spa centers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
