# Generated by Django 5.2.11 on 2026-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0010_historicalservice_historicalservicearrangement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='ideal_for_ar',
            field=models.CharField(blank=True, help_text="e.g., 'Relaxation', 'Pain Relief', 'Couples'", max_length=255, null=True, verbose_name='ideal for'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='ideal_for_en',
            field=models.CharField(blank=True, help_text="e.g., 'Relaxation', 'Pain Relief', 'Couples'", max_length=255, null=True, verbose_name='ideal for'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='service name'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='service name'),
        ),
        migrations.AddField(
            model_name='historicalspacenter',
            name='address_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='historicalspacenter',
            name='address_en',
            field=models.CharField(max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='historicalspacenter',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalspacenter',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalspacenter',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='branch name'),
        ),
        migrations.AddField(
            model_name='historicalspacenter',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='branch name'),
        ),
    ]
