# Generated by Django 5.2.11 on 2026-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0011_historicalservice_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='session_benefits',
            field=models.TextField(blank=True, default=None, help_text='Free-text description of session benefits', null=True, verbose_name='session benefits'),
        ),
        migrations.AddField(
            model_name='service',
            name='session_benefits',
            field=models.TextField(blank=True, default=None, help_text='Free-text description of session benefits', null=True, verbose_name='session benefits'),
        ),
    ]
