# Generated by Django 5.2.11 on 2026-06-25 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


def deduplicate_arrangements(apps, schema_editor):
    """
    Before applying the new (spa_center, arrangement_type, arrangement_label)
    unique constraint, collapse duplicate rows that exist because the OLD
    constraint included `service` (so the same type+label could repeat for
    different services at the same branch).

    Strategy:
    - Group rows by (spa_center_id, arrangement_type, arrangement_label).
    - Keep the first row (lowest created_at, or first UUID order).
    - Sum up room_count across duplicates so no capacity is lost.
    - Delete the duplicate rows (their TimeSlots are reassigned to the keeper).
    """
    ServiceArrangement = apps.get_model("spacenter", "ServiceArrangement")
    TimeSlot = apps.get_model("bookings", "TimeSlot")

    from collections import defaultdict

    # Build groups: key -> list of PKs ordered by created_at
    groups = defaultdict(list)
    for arr in ServiceArrangement.objects.order_by("created_at").values(
        "id", "spa_center_id", "arrangement_type", "arrangement_label", "room_count"
    ):
        key = (arr["spa_center_id"], arr["arrangement_type"], arr["arrangement_label"])
        groups[key].append(arr)

    for key, rows in groups.items():
        if len(rows) <= 1:
            continue  # no duplicates

        keeper = rows[0]
        duplicates = rows[1:]

        # Sum room_count across all duplicates into the keeper
        total_room_count = sum(r["room_count"] for r in rows)
        ServiceArrangement.objects.filter(id=keeper["id"]).update(
            room_count=total_room_count,
        )

        # Use raw SQL to reassign ALL foreign-keyed tables before deletion.
        # The ORM delete() is blocked by PROTECT FKs on promotions models.
        dup_ids = [str(r["id"]) for r in duplicates]
        keeper_id = str(keeper["id"])

        if not dup_ids:
            continue

        id_list = ", ".join(f"'{i}'" for i in dup_ids)

        with schema_editor.connection.cursor() as cursor:
            # TimeSlots
            cursor.execute(
                f"UPDATE bookings_timeslot SET arrangement_id = '{keeper_id}' "
                f"WHERE arrangement_id IN ({id_list})"
            )
            # Bookings
            cursor.execute(
                f"UPDATE bookings_booking SET service_arrangement_id = '{keeper_id}' "
                f"WHERE service_arrangement_id IN ({id_list})"
            )
            # GiftCards (promotions)
            cursor.execute(
                f"UPDATE promotions_giftcard SET service_arrangement_id = '{keeper_id}' "
                f"WHERE service_arrangement_id IN ({id_list})"
            )
            # LoyaltyCards (promotions)
            cursor.execute(
                f"UPDATE promotions_loyaltycard SET service_arrangement_id = '{keeper_id}' "
                f"WHERE service_arrangement_id IN ({id_list})"
            )
            # Promotions
            cursor.execute(
                f"UPDATE promotions_promotion SET service_arrangement_id = '{keeper_id}' "
                f"WHERE service_arrangement_id IN ({id_list})"
            )
            # Delete duplicates directly in SQL
            cursor.execute(
                f"DELETE FROM spacenter_servicearrangement WHERE id IN ({id_list})"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0013_service_booking_count'),
        ('bookings', '0013_historicalbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(help_text="Unique identifier for this room within the spa center (e.g. 'A1', 'VIP-01').", max_length=50, verbose_name='room ID')),
                ('name', models.CharField(max_length=100, verbose_name='room name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['spa_center', 'room_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicearrangement',
            options={'ordering': ['spa_center', 'arrangement_type'], 'verbose_name': 'service arrangement', 'verbose_name_plural': 'service arrangements'},
        ),
        migrations.RemoveIndex(
            model_name='servicearrangement',
            name='spacenter_s_spa_cen_107ab1_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicearrangement',
            name='spacenter_s_service_fbbfb4_idx',
        ),
        migrations.RunPython(
            code=deduplicate_arrangements,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='servicearrangement',
            unique_together={('spa_center', 'arrangement_type', 'arrangement_label')},
        ),
        migrations.AddField(
            model_name='historicalservicearrangement',
            name='allows_all_add_ons',
            field=models.BooleanField(default=True, help_text="If True, all add-ons defined on the booked service are available. If False, only add-ons in 'Allowed add-on services' are offered (acts as a filter on the service's own add-on list).", verbose_name='allows all add-ons'),
        ),
        migrations.AddField(
            model_name='historicalservicearrangement',
            name='allows_all_services',
            field=models.BooleanField(default=True, help_text="If True, any active service offered by this spa center can be booked in this arrangement. If False, only services listed in 'Allowed services' are accepted.", verbose_name='allows all services'),
        ),
        migrations.AddField(
            model_name='servicearrangement',
            name='allowed_add_on_services',
            field=models.ManyToManyField(blank=True, help_text="Specific add-ons permitted for bookings in this arrangement. Relevant only when 'Allows all add-ons' is False. Only add-ons that also exist on the booked service are shown.", related_name='whitelisted_arrangements', to='spacenter.addonservice', verbose_name='allowed add-on services'),
        ),
        migrations.AddField(
            model_name='servicearrangement',
            name='allowed_services',
            field=models.ManyToManyField(blank=True, help_text="Specific services that can use this arrangement. Relevant only when 'Allows all services' is False.", related_name='whitelisted_arrangements', to='spacenter.service', verbose_name='allowed services'),
        ),
        migrations.AddField(
            model_name='servicearrangement',
            name='allows_all_add_ons',
            field=models.BooleanField(default=True, help_text="If True, all add-ons defined on the booked service are available. If False, only add-ons in 'Allowed add-on services' are offered (acts as a filter on the service's own add-on list).", verbose_name='allows all add-ons'),
        ),
        migrations.AddField(
            model_name='servicearrangement',
            name='allows_all_services',
            field=models.BooleanField(default=True, help_text="If True, any active service offered by this spa center can be booked in this arrangement. If False, only services listed in 'Allowed services' are accepted.", verbose_name='allows all services'),
        ),
        migrations.AlterField(
            model_name='historicalservicearrangement',
            name='cleanup_duration',
            field=models.PositiveIntegerField(default=15, help_text='Time needed to clean/prepare the room after the service', verbose_name='cleanup duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='historicalservicearrangement',
            name='room_count',
            field=models.PositiveIntegerField(default=1, help_text="Legacy field: concurrent-booking capacity when no Room FK is set. Ignored when 'room' is assigned (capacity = 1 per room).", verbose_name='room count (legacy)'),
        ),
        migrations.AlterField(
            model_name='historicalservicearrangement',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Deprecated: kept for backwards compatibility. Use 'allowed services' / 'allows all services' instead.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='cleanup_duration',
            field=models.PositiveIntegerField(default=15, help_text='Time needed to clean/prepare the room after the service', verbose_name='cleanup duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='room_count',
            field=models.PositiveIntegerField(default=1, help_text="Legacy field: concurrent-booking capacity when no Room FK is set. Ignored when 'room' is assigned (capacity = 1 per room).", verbose_name='room count (legacy)'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Deprecated: kept for backwards compatibility. Use 'allowed services' / 'allows all services' instead.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrangements', to='spacenter.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='room',
            name='spa_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='spacenter.spacenter', verbose_name='spa center'),
        ),
        migrations.AddField(
            model_name='historicalservicearrangement',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The physical room this arrangement belongs to. When set, capacity is 1 (one session per arrangement). Leave blank only for legacy entries.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.room', verbose_name='room'),
        ),
        migrations.AddField(
            model_name='servicearrangement',
            name='room',
            field=models.ForeignKey(blank=True, help_text='The physical room this arrangement belongs to. When set, capacity is 1 (one session per arrangement). Leave blank only for legacy entries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='spacenter.room', verbose_name='room'),
        ),
        migrations.AddIndex(
            model_name='servicearrangement',
            index=models.Index(fields=['spa_center', 'is_active'], name='spacenter_s_spa_cen_bd2ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearrangement',
            index=models.Index(fields=['room', 'is_active'], name='spacenter_s_room_id_67522d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearrangement',
            index=models.Index(fields=['spa_center', 'arrangement_type', 'is_active'], name='spacenter_s_spa_cen_2a87d5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['spa_center', 'is_active'], name='spacenter_r_spa_cen_2410fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('spa_center', 'room_id')},
        ),
    ]
