# Generated by Django 5.2.11 on 2026-06-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0014_add_room_model_and_arrangement_whitelists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='room_count',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='service',
        ),
        migrations.AlterField(
            model_name='historicalservicearrangement',
            name='extra_minutes',
            field=models.CharField(choices=[('0', 'No extra time'), ('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='0', max_length=10, verbose_name='extra minutes'),
        ),
        migrations.AlterField(
            model_name='historicalservicearrangement',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The physical room this arrangement belongs to. Capacity is 1 (one session per arrangement).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='extra_minutes',
            field=models.CharField(choices=[('0', 'No extra time'), ('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='0', max_length=10, verbose_name='extra minutes'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='room',
            field=models.ForeignKey(help_text='The physical room this arrangement belongs to. Capacity is 1 (one session per arrangement).', on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='spacenter.room', verbose_name='room'),
        ),
    ]
