# Generated by Django 5.2.15 on 2026-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0016_service_session_benefits_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='add_on_services',
        ),
        migrations.AlterField(
            model_name='historicalservicearrangement',
            name='allows_all_add_ons',
            field=models.BooleanField(default=True, help_text="If True, all active add-ons in 'Allowed add-on services' are available for bookings in this arrangement. If False, add-ons must be explicitly listed below.", verbose_name='allows all add-ons'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='allowed_add_on_services',
            field=models.ManyToManyField(blank=True, help_text="Add-on services available for bookings in this arrangement. When 'Allows all add-ons' is True, all active entries here are offered. When False, only those explicitly listed are offered.", related_name='arrangements', to='spacenter.addonservice', verbose_name='allowed add-on services'),
        ),
        migrations.AlterField(
            model_name='servicearrangement',
            name='allows_all_add_ons',
            field=models.BooleanField(default=True, help_text="If True, all active add-ons in 'Allowed add-on services' are available for bookings in this arrangement. If False, add-ons must be explicitly listed below.", verbose_name='allows all add-ons'),
        ),
        migrations.AddIndex(
            model_name='baseproduct',
            index=models.Index(fields=['name_en'], name='spacenter_b_name_5d239d_idx-en'),
        ),
        migrations.AddIndex(
            model_name='baseproduct',
            index=models.Index(fields=['name_ar'], name='spacenter_b_name_5d239d_idx-ar'),
        ),
    ]
