# Generated by Django 5.2.11 on 2026-07-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0017_remove_add_on_services_from_service'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='baseproduct',
            name='spacenter_b_name_5d239d_idx-en',
        ),
        migrations.RemoveIndex(
            model_name='baseproduct',
            name='spacenter_b_name_5d239d_idx-ar',
        ),
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='discount_price',
        ),
    ]
