# Generated by Django 5.2.11 on 2026-07-05 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0018_remove_baseproduct_spacenter_b_name_5d239d_idx_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='allows_all_add_ons',
        ),
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='allows_all_services',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='allowed_add_on_services',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='allowed_services',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='allows_all_add_ons',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='allows_all_services',
        ),
        migrations.CreateModel(
            name='ServiceArrangementAddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('add_on_services', models.ManyToManyField(related_name='arrangement_addons', to='spacenter.addonservice', verbose_name='add-on services')),
                ('service_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='spacenter.servicearrangement', verbose_name='service arrangement')),
            ],
            options={
                'verbose_name': 'service arrangement add-on',
                'verbose_name_plural': 'service arrangement add-ons',
            },
        ),
        migrations.CreateModel(
            name='ServiceArrangementPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discounted price')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangement_prices', to='spacenter.service', verbose_name='service')),
                ('service_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='spacenter.servicearrangement', verbose_name='service arrangement')),
            ],
            options={
                'verbose_name': 'service arrangement price',
                'verbose_name_plural': 'service arrangement prices',
                'unique_together': {('service', 'service_arrangement')},
            },
        ),
    ]
