# Generated by Django 5.2.11 on 2026-07-05 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenter', '0019_remove_historicalservicearrangement_allows_all_add_ons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='extra_minutes',
        ),
        migrations.RemoveField(
            model_name='historicalservicearrangement',
            name='price_for_extra_minutes',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='extra_minutes',
        ),
        migrations.RemoveField(
            model_name='servicearrangement',
            name='price_for_extra_minutes',
        ),
        migrations.AddField(
            model_name='servicearrangementprice',
            name='extra_minutes',
            field=models.CharField(choices=[('0', 'No extra time'), ('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='0', max_length=10, verbose_name='extra minutes'),
        ),
        migrations.AddField(
            model_name='servicearrangementprice',
            name='price_for_extra_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use base price for extra minutes', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price for extra minutes'),
        ),
    ]
