# Generated by Django 5.2.10 on 2026-02-07 11:01

import bookings.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('spacenter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(default=bookings.models.generate_order_number, editable=False, max_length=25, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of item prices before discounts', max_digits=10, verbose_name='total amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied (vouchers + other)', max_digits=10, verbose_name='discount amount')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final payable amount after discounts', max_digits=10, verbose_name='final amount')),
                ('currency', models.CharField(default='QAR', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(blank=True, help_text='Method used for payment (e.g., Credit Card, Cash)', max_length=50, verbose_name='payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gift_cards', models.ManyToManyField(blank=True, related_name='product_orders', to='promotions.giftcard', verbose_name='gift cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('vouchers', models.ManyToManyField(blank=True, related_name='product_orders', to='promotions.voucher', verbose_name='vouchers')),
            ],
            options={
                'verbose_name': 'product order',
                'verbose_name_plural': 'product orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of purchase', max_digits=10, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Quantity * Unit Price', max_digits=10, verbose_name='total price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='spacenter.spaproduct', verbose_name='product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.productorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='spacenter.servicearrangement', verbose_name='service arrangement')),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_index=True, default=bookings.models.generate_booking_number, max_length=25, unique=True, verbose_name='booking number')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total price')),
                ('customer_message', models.TextField(blank=True, help_text='Special requests or notes from customer', verbose_name='customer message')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes for staff', verbose_name='staff notes')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('payment_pending', 'Payment Pending'), ('payment_success', 'Payment Success'), ('confirmed', 'Confirmed'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='requested', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('add_on_services', models.ManyToManyField(blank=True, related_name='bookings', to='spacenter.addonservice', verbose_name='add-on services')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('service_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='spacenter.servicearrangement', verbose_name='service arrangement')),
                ('spa_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='spacenter.spacenter', verbose_name='spa center')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='spacenter.therapistprofile', verbose_name='therapist')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.timeslot', verbose_name='time slot')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['arrangement', 'date', 'start_time'], name='bookings_ti_arrange_49e734_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='bookings_ti_date_7ce269_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='bookings_bo_custome_0cbf77_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['spa_center', 'status'], name='bookings_bo_spa_cen_3c7b01_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
    ]
