# Generated by Django 5.2.10 on 2026-01-19 09:29

import bookings.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spacenter", "0004_addonservice_description_ar_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceArrangement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_no",
                    models.CharField(
                        help_text="Room label for this arrangement",
                        max_length=100,
                        verbose_name="room number",
                    ),
                ),
                (
                    "arrangement_type",
                    models.CharField(
                        choices=[
                            ("single_room", "Single Room"),
                            ("couple_room", "Couple Room"),
                            ("group_room", "Group Room"),
                            ("open_area", "Open Area"),
                            ("vip_suite", "VIP Suite"),
                            ("outdoor_arrangement", "Outdoor Arrangement"),
                        ],
                        default="single_room",
                        max_length=25,
                        verbose_name="arrangement type",
                    ),
                ),
                (
                    "arrangement_label",
                    models.CharField(
                        help_text="Display label for this arrangement",
                        max_length=100,
                        verbose_name="arrangement label",
                    ),
                ),
                (
                    "cleanup_duration",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Time needed to clean/prepare room after service",
                        verbose_name="cleanup duration (minutes)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrangements",
                        to="spacenter.service",
                        verbose_name="service",
                    ),
                ),
                (
                    "spa_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_arrangements",
                        to="spacenter.spacenter",
                        verbose_name="spa center",
                    ),
                ),
            ],
            options={
                "verbose_name": "service arrangement",
                "verbose_name_plural": "service arrangements",
                "ordering": ["spa_center", "service", "room_no"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "arrangement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="bookings.servicearrangement",
                        verbose_name="service arrangement",
                    ),
                ),
            ],
            options={
                "verbose_name": "time slot",
                "verbose_name_plural": "time slots",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        db_index=True,
                        default=bookings.models.generate_booking_number,
                        max_length=25,
                        unique=True,
                        verbose_name="booking number",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="total price",
                    ),
                ),
                (
                    "customer_message",
                    models.TextField(
                        blank=True,
                        help_text="Special requests or notes from customer",
                        verbose_name="customer message",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for staff",
                        verbose_name="staff notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_success", "Payment Success"),
                            ("confirmed", "Confirmed"),
                            ("on_hold", "On Hold"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "add_on_services",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookings",
                        to="spacenter.addonservice",
                        verbose_name="add-on services",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "spa_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="spacenter.spacenter",
                        verbose_name="spa center",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="spacenter.therapistprofile",
                        verbose_name="therapist",
                    ),
                ),
                (
                    "service_arrangement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.servicearrangement",
                        verbose_name="service arrangement",
                    ),
                ),
                (
                    "time_slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking",
                        to="bookings.timeslot",
                        verbose_name="time slot",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="servicearrangement",
            index=models.Index(
                fields=["spa_center", "service", "is_active"],
                name="bookings_se_spa_cen_c40bea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicearrangement",
            index=models.Index(
                fields=["service", "is_active"], name="bookings_se_service_198126_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicearrangement",
            unique_together={("spa_center", "service", "room_no")},
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["arrangement", "date", "start_time"],
                name="bookings_ti_arrange_49e734_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["date", "start_time", "end_time"],
                name="bookings_ti_date_7ce269_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "status"], name="bookings_bo_custome_0cbf77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["spa_center", "status"], name="bookings_bo_spa_cen_3c7b01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="bookings_bo_status_72dd85_idx"
            ),
        ),
    ]
