# Generated by Django 5.2.10 on 2026-02-07 07:31

import bookings.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('promotions', '0003_add_recipient_phone'),
        ('spacenter', '0004_addonservice_description_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(default=bookings.models.generate_order_number, editable=False, max_length=25, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of item prices before discounts', max_digits=10, verbose_name='total amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied (vouchers + other)', max_digits=10, verbose_name='discount amount')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final payable amount after discounts', max_digits=10, verbose_name='final amount')),
                ('currency', models.CharField(default='QAR', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(blank=True, help_text='Method used for payment (e.g., Credit Card, Cash)', max_length=50, verbose_name='payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('gift_cards', models.ManyToManyField(blank=True, related_name='product_orders', to='promotions.giftcard', verbose_name='gift cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('vouchers', models.ManyToManyField(blank=True, related_name='product_orders', to='promotions.voucher', verbose_name='vouchers')),
            ],
            options={
                'verbose_name': 'product order',
                'verbose_name_plural': 'product orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of purchase', max_digits=10, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Quantity * Unit Price', max_digits=10, verbose_name='total price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='spacenter.spaproduct', verbose_name='product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.productorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
