# Generated by Django 5.2.11 on 2026-02-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="therapist",
        ),
    ]
