# Generated by Django 5.2.10 on 2026-02-08 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied (vouchers + other)', max_digits=10, verbose_name='discount amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gift_cards',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='promotions.giftcard', verbose_name='gift cards'),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of service prices before discounts', max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vouchers',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='promotions.voucher', verbose_name='vouchers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Final payable amount after discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total price'),
        ),
    ]
