# Generated by Django 5.2.10 on 2026-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_discount_amount_booking_gift_cards_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gift_cards',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vouchers',
        ),
        migrations.AddField(
            model_name='booking',
            name='gift_card_transactions',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='promotions.giftcardtransaction', verbose_name='gift card transactions'),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_usages',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='promotions.voucherusage', verbose_name='voucher usages'),
        ),
    ]
