# Generated by Django 5.2.11 on 2026-02-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_booking_therapist"),
        ("spacenter", "0003_remove_service_extra_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="add_on_services",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="gift_card_transactions",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="voucher_usages",
        ),
        migrations.AddField(
            model_name="booking",
            name="meta_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible JSON data for add-ons, vouchers, gift cards, and other extras",
                verbose_name="metadata",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="spacenter.service",
                verbose_name="service",
            ),
        ),
    ]
