# Generated by Django 5.2.10 on 2026-02-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_productorder_orderitem'),
        ('spacenter', '0005_add_servicearrangement_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='spacenter.servicearrangement', verbose_name='service arrangement'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_arrangement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='spacenter.servicearrangement', verbose_name='service arrangement'),
        ),
        migrations.DeleteModel(
            name='ServiceArrangement',
        ),
    ]
