# Generated by Django 5.2.11 on 2026-02-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_remove_booking_add_on_services_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extra_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Extra minutes added to the service duration",
                verbose_name="extra minutes",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price_for_extra_minutes",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price charged for the extra minutes",
                max_digits=10,
                verbose_name="price for extra minutes",
            ),
        ),
    ]
