# Generated by Django 5.2.11 on 2026-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_extra_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_duration",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total duration in minutes (service duration + extra minutes)",
                verbose_name="total duration (minutes)",
            ),
        ),
    ]
