# Generated by Django 5.2.11 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_total_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productorder",
            name="vouchers",
        ),
        migrations.AlterField(
            model_name="booking",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total discount applied",
                max_digits=10,
                verbose_name="discount amount",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="meta_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible JSON data for add-ons, gift cards, and other extras",
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="productorder",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total discount applied",
                max_digits=10,
                verbose_name="discount amount",
            ),
        ),
    ]
