# Generated by Django 5.2.11 on 2026-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_remove_productorder_vouchers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productorder",
            name="gift_cards",
        ),
    ]
