# Generated by Django 5.2.11 on 2026-03-02 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_remove_productorder_gift_cards"),
        ("promotions", "0008_alter_loyaltyreward_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_loyalty_reward",
            field=models.BooleanField(
                default=False,
                help_text="Whether this booking was created by redeeming a loyalty reward",
                verbose_name="is loyalty reward",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="loyalty_reward",
            field=models.ForeignKey(
                blank=True,
                help_text="The loyalty reward redeemed for this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loyalty_bookings",
                to="promotions.loyaltyreward",
                verbose_name="loyalty reward",
            ),
        ),
    ]
