# Generated by Django 5.2.11 on 2026-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_is_loyalty_reward_booking_loyalty_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="contact_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number of the person receiving the delivery",
                max_length=20,
                verbose_name="contact number",
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Delivery fee added to the order",
                max_digits=10,
                verbose_name="delivery charge",
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="shipping_address",
            field=models.TextField(
                blank=True,
                help_text="Delivery address for the order",
                verbose_name="shipping address",
            ),
        ),
    ]
