# Generated by Django 5.2.11 on 2026-03-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_productorder_contact_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productorder",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="productorder",
            name="payment_method",
        ),
        migrations.AlterField(
            model_name="productorder",
            name="final_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Final payable amount",
                max_digits=10,
                verbose_name="final amount",
            ),
        ),
    ]
