# Generated by Django 5.2.11 on 2026-03-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_remove_productorder_discount_amount_and_more"),
        ("promotions", "0008_alter_loyaltyreward_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="gift_card",
            field=models.ForeignKey(
                blank=True,
                help_text="The gift card redeemed for this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gift_card_bookings",
                to="promotions.giftcard",
                verbose_name="gift card",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_gift_card",
            field=models.BooleanField(
                default=False,
                help_text="Whether this booking was created by redeeming a gift card",
                verbose_name="is gift card",
            ),
        ),
    ]
