# Generated by Django 5.2.11 on 2026-03-31 07:41

import bookings.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_booking_gift_card_booking_is_gift_card"),
        ("spacenter", "0005_homeservice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeServiceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        db_index=True,
                        default=bookings.models.generate_home_booking_number,
                        max_length=25,
                        unique=True,
                        verbose_name="booking number",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                ("time", models.TimeField(verbose_name="time")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Sum of service prices before discounts",
                        max_digits=10,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total discount applied",
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "extra_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra minutes added to the service duration",
                        verbose_name="extra minutes",
                    ),
                ),
                (
                    "price_for_extra_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price charged for the extra minutes",
                        max_digits=10,
                        verbose_name="price for extra minutes",
                    ),
                ),
                (
                    "total_duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total duration in minutes (service duration + extra minutes)",
                        verbose_name="total duration (minutes)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final payable amount after discounts",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="total price",
                    ),
                ),
                (
                    "home_location",
                    models.TextField(
                        help_text="Full address / location where service will be delivered",
                        verbose_name="home location",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        help_text="Phone number to contact for the booking",
                        max_length=20,
                        verbose_name="contact number",
                    ),
                ),
                (
                    "customer_message",
                    models.TextField(
                        blank=True,
                        help_text="Special requests or notes from customer",
                        verbose_name="customer message",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for staff",
                        verbose_name="staff notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_success", "Payment Success"),
                            ("confirmed", "Confirmed"),
                            ("on_hold", "On Hold"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_service_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "home_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="spacenter.homeservice",
                        verbose_name="home service",
                    ),
                ),
            ],
            options={
                "verbose_name": "home service booking",
                "verbose_name_plural": "home service bookings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"],
                        name="bookings_ho_custome_fc54fa_idx",
                    ),
                    models.Index(
                        fields=["home_service", "status"],
                        name="bookings_ho_home_se_558ad5_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="bookings_ho_status_669f6c_idx",
                    ),
                    models.Index(
                        fields=["date", "status"], name="bookings_ho_date_06edee_idx"
                    ),
                ],
            },
        ),
    ]
