# Generated by Django 5.2.11 on 2026-04-23 08:28

import bookings.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_homeservicebooking'),
        ('promotions', '0011_alter_giftcard_status'),
        ('spacenter', '0010_historicalservice_historicalservicearrangement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('booking_number', models.CharField(db_index=True, default=bookings.models.generate_booking_number, max_length=25, verbose_name='booking number')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of service prices before discounts', max_digits=10, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied', max_digits=10, verbose_name='discount amount')),
                ('extra_minutes', models.PositiveIntegerField(default=0, help_text='Extra minutes added to the service duration', verbose_name='extra minutes')),
                ('price_for_extra_minutes', models.DecimalField(decimal_places=2, default=0.0, help_text='Price charged for the extra minutes', max_digits=10, verbose_name='price for extra minutes')),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Total duration in minutes (service duration + extra minutes)', verbose_name='total duration (minutes)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Final payable amount after discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total price')),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Flexible JSON data for add-ons, gift cards, and other extras', verbose_name='metadata')),
                ('customer_message', models.TextField(blank=True, help_text='Special requests or notes from customer', verbose_name='customer message')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes for staff', verbose_name='staff notes')),
                ('is_loyalty_reward', models.BooleanField(default=False, help_text='Whether this booking was created by redeeming a loyalty reward', verbose_name='is loyalty reward')),
                ('is_gift_card', models.BooleanField(default=False, help_text='Whether this booking was created by redeeming a gift card', verbose_name='is gift card')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('payment_pending', 'Payment Pending'), ('payment_success', 'Payment Success'), ('confirmed', 'Confirmed'), ('on_hold', 'On Hold'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='requested', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('gift_card', models.ForeignKey(blank=True, db_constraint=False, help_text='The gift card redeemed for this booking', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promotions.giftcard', verbose_name='gift card')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loyalty_reward', models.ForeignKey(blank=True, db_constraint=False, help_text='The loyalty reward redeemed for this booking', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='promotions.loyaltyreward', verbose_name='loyalty reward')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.service', verbose_name='service')),
                ('service_arrangement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.servicearrangement', verbose_name='service arrangement')),
                ('spa_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='spacenter.spacenter', verbose_name='spa center')),
                ('time_slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.timeslot', verbose_name='time slot')),
            ],
            options={
                'verbose_name': 'historical booking',
                'verbose_name_plural': 'historical bookings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
